### ISSUE TITLE
להוסיף מפלגה" בשם "ועדת הכנסת המשותפת לעניינים ביומטריים"

### ISSUE THREAD

**Issue by Osialot** [no2bio/mk-personal#12]
ולהכין סט אחר של מכתבים/טוויטים/פיסושים וכו לחברי/חברות ועדה בעד/נגד/מתלבטים
אפילו עם "פוסטר" טוויט/פייס ייחדי עבור כל ח"כ. יש שישה

**Comment by thedod** [comment]
Oops. I reopen this, because we'll also want customised letters for them, etc. Anyway, it's a temporary fix:

http://dropthepilot.no2bio.org/?party=_vaadat_huka#mk-status

**Comment by thedod** [comment]
Now we also need to import latest csv into googledocs (@michbarsinai - is it easy?) and add the other vaadot that we want (do we?). You can enter `_vaada_a,_vaada_b` to `vaadot` because it does a `search()` (not `===`)

**Comment by thedod** [comment]
Loose ends split into #29 and #30
