### ISSUE TITLE
"poster" for fb/tweeter

### ISSUE THREAD

**Issue by thedod** [no2bio/mk-personal#13]
When we share pages from the site in fb, [this placeholder](https://github.com/no2bio/mk-personal/blob/gh-pages/img/poster.jpg) is the image that will appear. Same in twitter (twittercard).
Ignore proportions. Do something that would look good on fb (and will be very small in twitter, but never mind that :wink:)

**Comment by thedod** [comment]
That's the _real_ reason we wanted @Osialot to join: you can't assign a ticket to a non-member :tongue:

**Comment by Osialot** [comment]
its assigned n e way, by the Hindra itself :tongue:

**Comment by Osialot** [comment]
Do we have a final url? i need it for the poster

**Comment by michbarsinai** [comment]
final URL: 
http://dropthepilot.no2bio.org

**Comment by michbarsinai** [comment]
Note that it's not up yet, just final.

**Comment by Osialot** [comment]
check ur emails

**Comment by thedod** [comment]
Thanks.
