### ISSUE TITLE
CNAME and domain

### ISSUE THREAD

**Issue by michbarsinai** [no2bio/mk-personal#2]
Put the site under `dropthepilot.no2bio.com`.

**Comment by thedod** [comment]
DNS started crunching on it, but let's wait for #8 before CNAME

**Comment by thedod** [comment]
OK. We waits for #13 and #3 (and maybe the phone shenanigans) and then :tada:
@michbarsinai &mdash; when you feel the time is right, :scissors:  "cut the ribbon" and commit `CNAME`.
