### ISSUE TITLE
Separate image for tweets

### ISSUE THREAD

**Issue by thedod** [no2bio/mk-personal#24]
our [poster](http://dropthepilot.no2bio.org/img/poster.jpg) looks great on fb, but twitter does 2 nasty things:
- Crops it to be [4x3](https://o.twimg.com/2/proxy.jpg?t=HBgtaHR0cDovL2Ryb3B0aGVwaWxvdC5ubzJiaW8ub3JnL2ltZy9wb3N0ZXIuanBnFJgLFLIIHBTwARS0AQAAFgASAA&s=FAusLd3kqzfOvQ9bSfwIpU-7W4fjkatPB0zxY1MY_sA) (cutting some text. looks kinda sloppy)
- [At least on my desktop] reduces it to 109x82 (no text is readable at that size)

I suggest something twitter-specific, 1024x768 (even 800x600), maybe even png with transparency (if you think it's useful). No place for text (unless it's as short as "No2Bio" :wink:).

**Comment by thedod** [comment]
Meanwhile, there's a "placeholder picture" [here](https://github.com/no2bio/mk-personal/blob/b23b6df5d483df090303ac08dcccdd67d65cf52e/img/poster-4x3.jpg).

**Comment by Osialot** [comment]
Actually i think its a great place holder

**Comment by thedod** [comment]
Thanks :relieved:. We'll do an official tweet (with the original non-4x3 poster as image), so that we have its url as "tweet-fodder".
