### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by michbarsinai** [no2bio/mk-personal#3]
We can use GoogleAnalytics, or any other thing available.

**Comment by thedod** [comment]
I have a feeling this sorta got stuck because y'all assumed I knew how to do these things :wink:. @michbarsinai, :pray: please help me out here. Do whatever you usually do with google. I'm sure it's better than what _I_ would have done with them.

**Comment by michbarsinai** [comment]
@thedod I disagree, but that would at lest be legal.
