### ISSUE TITLE
Google docs should become master again

### ISSUE THREAD

**Issue by thedod** [no2bio/mk-personal#30]
We should import latest csvs (mks, parties) into googledocs (@michbarsinai - is it easy?)
but not yet :wink:
I'm turning a few MKs green with tweet references.
I'll comment here when done.

**Comment by michbarsinai** [comment]
no no no no!!!!!! We've diverted here, and need to re-join.

The googleodc is updated with a committee membership. I'll post a new version shortly. Update there, but don't override any columns or parsing code in ctrl.js.

**Comment by thedod** [comment]
Back. False alarm. Tweets added references, but no color changes (except yelin's green for a few hours now). Googledoc can officially be master now.

**Comment by michbarsinai** [comment]
Great. Pushing in a sec.

**Comment by thedod** [comment]
Still need to sync a few things
- yelin is green (already on googledoc, next update-mks it's done)
- 3 MKs we suddenly saw on TV are actually in "tat vaadat bitachon yada yada" (so originally I just added them "solo" to meshutefet)
  - nissan (runs the show)
  - avidichter
  - tzhanegbi
